# Generated by Django 4.1 on 2024-10-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="core.tag", verbose_name="Tags"
            ),
        ),
    ]
